---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-deploy
  labels:
    myversion: "1"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: clinic-front
  template:
    metadata:
      labels:
        app: clinic-front
    spec: # specification du pod
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: springboot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.app.contextPath | default "/" | quote }}

          startupProbe:
            httpGet:
              path: {{ .Values.app.contextPath }}/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: {{ .Values.app.contextPath }}/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: {{ .Values.app.contextPath }}/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
            timeoutSeconds: 2