---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clinic-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{ .Values.app.contextPath | default "/" }}
        backend:
          service:
            name: clinic-service
            port:
              number: {{ .Values.service.port }}